### ISSUE TITLE
Performance under scale for 'not found'

### ISSUE THREAD

**Issue by mmicco-godaddy** [maxmind/GeoIP2-dotnet#11]
From documentation:
If an address is not available in the database, a AddressNotFoundException will be thrown.

If you have a hit rate that is high, throwing an exception for an IP city not found would probably be negligble. But, depending on your miss rate, an exception can be an unnecessary overhead expense on your code performance. Should a way to receive a result that indicates 'not found' vs an exception be supported?

**Comment by manigandham** [comment]
This is resolved in #50 which adds Try... lookup methods. This follows the idiomatic pattern of other .NET methods like TryParse which use an `out` parameter for the value and return a `bool` for the result of the lookup attempt.
