### ISSUE TITLE
No Async support in DatabaseReader?

### ISSUE THREAD

**Issue by AachoLoya** [maxmind/GeoIP2-dotnet#136]
I'm adding GeoIP2 (city database) lookup support in asp.net webapi, but don't see any async methods? Async is a much more efficient programming paradigm for server environments, so how come there is no async support?

**Comment by oschwald** [comment]
The database files are either memory mapped or read from memory. There are not async IO APIs for either in .NET. If you are worried about the initial file IO when creating the reader, you can first load the database into memory and pass a stream to the reader.
