### ISSUE TITLE
Separate local database and Web API in different DLLs

### ISSUE THREAD

**Issue by Mailaender** [maxmind/GeoIP2-dotnet#16]
We are using your cool GeoLite2 databases in our Open Source RTS game engine recreation project @OpenRA since version 1 of your .NET API:
- https://github.com/OpenRA/OpenRA/pull/6902
- https://github.com/OpenRA/OpenRA/pull/4666
- https://github.com/OpenRA/OpenRA/pull/3647

Thanks for that already!

We now depend on Newtonsoft.Json.dll and RestSharp.dll although we don't use any JSON or REST anywhere in the game. It is just a hard dependency of your GeoIP2 library. Therefore I suggest to separate the local database parsing and the Web API into separate DLLs of the same project so we and others can avoid unnecessary dependencies.

**Comment by oschwald** [comment]
I am going to close this issue as we no longer use RestSharp and the plan is to replace Json.NET with `System.Text.Json` once version 5 is available.
