### ISSUE TITLE
Not working with RestSharp 105.0.1

### ISSUE THREAD

**Issue by geofili** [maxmind/GeoIP2-dotnet#17]
I have updated my project using NuGet to the latest MaxMind.db & MaxMind.GeoIP2 and RestSharp.

When I executing the code:

    MaxMind.GeoIP2.Responses.CountryResponse country;
    country = DBReader.Country(ipAddress);

I get the following exception:

    [System.IO.FileNotFoundException] = {"Could not load file or assembly 'RestSharp, Version=105.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.":"RestSharp, Version=105.0.0.0, Culture=neutral, PublicKeyToken=null"}

I have downgraded RestSharp back to 105.0.0 which is working ok.

**Comment by niemyjski** [comment]
:+1:

**Comment by nSource** [comment]
I ran into the same issue.

**Comment by niemyjski** [comment]
If I do a pull request for this, will you guys accept it?

**Comment by oschwald** [comment]
Would the pull request just update the project to depend on 105.0.1? Master is already at that version. We just need to do a release.

**Comment by niemyjski** [comment]
Yes, so it sounds like you just need to do a release

Sent from Outlook




On Fri, May 1, 2015 at 12:14 PM -0700, "Gregory Oschwald" <notifications@github.com> wrote:












Would the pull request just update the project to depend on 105.0.1? Master is already at that version. We just need to do a release.

**Comment by oschwald** [comment]
We did a release with update dependencies, among other things.

**Comment by ayberkcanturk** [comment]
Hello there,

I have the same error.

An unhandled exception of type 'System.IO.FileNotFoundException' occurred in cvdb.Framework.Localization.dll Additional information: 'RestSharp, Version=105.1.0.0, Culture=neutral, PublicKeyToken=null'.

I have checked the bin folder. Assembly is there.
