### ISSUE TITLE
RestSharp 105.1.0.0  

### ISSUE THREAD

**Issue by ayberkcanturk** [maxmind/GeoIP2-dotnet#29]
Hello there,

I have downloaded GeoIP2-dotnet by nuget with depended assemblies. When I execute the following code:

int userID = "***";
string licenseKey = "***";
string ip = "***";

private readonly WebServiceClient client;
client = new WebServiceClient(userID, licenseKey);

CountryResponse response = client.Country(ip);

I get following exception at the last line of the code:

An unhandled exception of type 'System.IO.FileNotFoundException' occurred in ***.Framework.Localization.dll

[System.IO.FileNotFoundException] = {"Could not load file or assembly 'RestSharp, Version=105.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.":"RestSharp, Version=105.1.0.0, Culture=neutral, PublicKeyToken=null"}

I have checked the bin if the assembly is there. And I have seen assembly is there and there is no error in references and packages.config. What is the problem?

Thanks

**Comment by oschwald** [comment]
Are you using the beta or the latest production version?

**Comment by ayberkcanturk** [comment]
Hello oschwald,

I am using the latest version. I have used "install-package MaxMind.GeoIP2" command for installing.

**Comment by oschwald** [comment]
Could you try installing the pre-release version by running:

```
Install-Package MaxMind.GeoIP2 –IncludePrerelease
```

**Comment by ayberkcanturk** [comment]
I have realized that I have different versions in framework and application bin folder. It is working now with RestSharp 105.1.0.0.  Thank you for your time.

**Comment by oschwald** [comment]
Thanks for letting us know. Closing.
