### ISSUE TITLE
Json Serialization Drops Name fields

### ISSUE THREAD

**Issue by jaszudy** [maxmind/GeoIP2-dotnet#41]
When I create a DatabaseReader object and complete a search for an IP that exists in the database, the CityResponse object contains values for the .Name fields.  For example, CityResponse.City.Name =SomeCity.  When I serialize this object using  JsonConvert.SerializeObject(CityResponse) (part of Newtonsoft.Json.dll), the Name properties are not serialized.  If I then use JsonConvert.DeserializeObject<CityResponse>(jsonstring) to deserialize back to the object the .Name fields are null.  Is there a way to ensure that the .Name fields are serialized with the rest of the object?

Example:
 var city = loReader.City(lstrIP); // city.City.Name = cityname
var json = JsonConvert.SerializeObject(city); 
var city2 = JsonConvert.DeserializeObject<MaxMind.GeoIP2.Responses.CityResponse>(json); //city2.City.Name = null

**Comment by oschwald** [comment]
Thanks for the report. This seems like something that should be fixed.
