### ISSUE TITLE
NuGet version compiled against .NET Framework 4.5

### ISSUE THREAD

**Issue by Mailaender** [maxmind/GeoIP2-dotnet#44]
It looks like we are forced to use Framework version 4.5.2 if we want to support .NET and Visual Studio, and forced to use 4.5 if we want to support MonoDevelop and Mono for https://github.com/OpenRA/OpenRA/pull/10280 Could you add a `net45` folder to the NuGet package to get us out of this dependency hell?

**Comment by oschwald** [comment]
Microsoft's end of life for 4.5 is January 12, 2016. Could you force the Mono version you are using to treat it as 4.5?

**Comment by Mailaender** [comment]
Mono or rather xbuild only understands the major version as targets and seems to be missing a redirect:

![image](https://cloud.githubusercontent.com/assets/756669/12003459/73541a30-ab1f-11e5-885b-2d39d4bf2ffd.png)


I filed a bug at https://bugzilla.xamarin.com/show_bug.cgi?id=37286 but that probably won't get addressed any time soon.

**Comment by Mailaender** [comment]
This will also stop you from entering the major Linux distribution repositories: https://bugzilla.redhat.com/show_bug.cgi?id=1279085

**Comment by oschwald** [comment]
If you are building it from source, as most distributions do, you can just pass the target framework to xbuild, e.g., `xbuild /p:TargetFrameworkVersion="v4.5"`.

**Comment by RonSell** [comment]
Is the same issue?

Could not install package 'MaxMind.GeoIP2 2.5.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by oviwankenobi** [comment]
I am seeing this problem when I try to run this command, can you please advice how to get around it? thank you.

PM> Install-Package MaxMind.GeoIP2 -Version 2.5.0
Attempting to resolve dependency 'MaxMind.Db (≥ 1.2.0)'.
Attempting to resolve dependency 'Newtonsoft.Json (≥ 7.0.1)'.
Installing 'MaxMind.GeoIP2 2.5.0'.
Successfully installed 'MaxMind.GeoIP2 2.5.0'.
Adding 'MaxMind.Db 1.2.0' to ProbeAPIService.
Successfully added 'MaxMind.Db 1.2.0' to ProbeAPIService.
Adding 'MaxMind.GeoIP2 2.5.0' to ProbeAPIService.
Uninstalling 'MaxMind.GeoIP2 2.5.0'.
Successfully uninstalled 'MaxMind.GeoIP2 2.5.0'.
Install failed. Rolling back...
**_Install-Package : Could not install package 'MaxMind.GeoIP2 2.5.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references 
or content files that are compatible with that framework. For more information, contact the package author._**
At line:1 char:1
+ Install-Package MaxMind.GeoIP2 -Version 2.5.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by oschwald** [comment]
2.5.0 required .NET 4.5.2. Try `Install-Package MaxMind.GeoIP2 -Pre` to get the latest beta, which relaxes the requirement to 4.5.

**Comment by oviwankenobi** [comment]
I will go ahead with 2.4 cause I do not how stable the beta is and we really do not need any surprises.
is it known the release of the 2.6 ?

**Comment by oschwald** [comment]
We don't have a set release date for 2.6, but there are no known issues with it.
