### ISSUE TITLE
Retrieving "parent" CIDR block for an IP

### ISSUE THREAD

**Issue by sarus** [maxmind/GeoIP2-dotnet#54]
Is there a way to retrieve the parent CIDR block for an IP address? In other words, the largest CIDR block where every address in that block has the same geolocation and ownership information of the IP being looked up.

Thanks!

**Comment by oschwald** [comment]
No, this is not currently possible. It would be reasonably easy to implement as an additional lookup method, although it might make sense to provide it at the `MaxMind.Db`level rather than in this library.

**Comment by sarus** [comment]
Thanks for such a quick response and providing a great library and service to the community.

**Comment by sarus** [comment]
Sorry, I closed prematurely.  Do you recommend doing manual lookups to the database in both directions to find the range that has the same ownerhsip and geolocation info?

Something like:

```
Lookup 5.6.7.8  --> Result "A"
Lookup 5.6.7.7 --> Result "A"
Lookup 5.6.7.9 --> Result "A"
Lookup 5.6.7.6 --> Result "A"
Lookup 5.6.7.5 --> Result "B"
Lookup 5.6.7.10 --> Result "B"

Range is 5.6.7.6-5.6.7.9
```

**Comment by oschwald** [comment]
@sarus, if you need this feature. I'd recommend submitting a PR against [MaxMind.Db](https://github.com/maxmind/MaxMind-DB-Reader-dotnet) to add it there as an `out` variable on a new lookup method or something. You can obtain it during the [tree traversal](https://github.com/maxmind/MaxMind-DB-Reader-dotnet/blob/master/MaxMind.Db/Reader.cs#L181).

Sequentially looking up each IP address is going to be very slow unless you are only concerned about a small network.

**Comment by oschwald** [comment]
This information is also available in our CSVs.

**Comment by sarus** [comment]
ok thank you!
