### ISSUE TITLE
install Problem(install-package MaxMind.GeoIP2)

### ISSUE THREAD

**Issue by Ethirajparthasarathi** [maxmind/GeoIP2-dotnet#57]
![error](https://cloud.githubusercontent.com/assets/18160446/14134123/5837873e-f672-11e5-8d98-7621cf8935b7.PNG)

I will try install the maxmind.geoIP but not install maxmind.geoip show on the error. That error screen short herewith attached,so kindly verify the problem and also I am using only asp.net 4.5 frame work (visual studio 2012)only.

already added the elmah reference also.

**Comment by oschwald** [comment]
2.5.0 targets 4.5.2 as Microsoft has EOL'd 4.5. However, in the 2.6 beta, we walked this back a bit to 4.5. I would recommend either using the latest beta or 2.4.

**Comment by Ethirajparthasarathi** [comment]
Hi oschwald ,

First of all thanks for your reply .
Ya, I got your point.but how is install the latest beta or 2.4.
if you know any link or Url path.(give the details for step by step)

**Comment by oschwald** [comment]
In the NuGet console, type `Install-Package MaxMind.GeoIP2 -Pre` for the beta or `Install-Package MaxMind.GeoIP2 -Version 2.4.0` for 2.4.0.

**Comment by Ethirajparthasarathi** [comment]
Hi oschwald ,

Most of maxmind is GEOIP2 product is support for PHP,Python and Java related only more.
Maxmind GeoIp2 product is support for C# and Asp.net project
If support means give the sample GeoIP2 product for Asp.net,C# sample code

**Comment by Ethirajparthasarathi** [comment]
![nuget](https://cloud.githubusercontent.com/assets/18160446/14178824/fafc1d88-f779-11e5-9296-d177cb070caf.PNG)

I will try this way but not install ya(In the NuGet console, type Install-Package MaxMind.GeoIP2 -Pre for the beta or Install-Package MaxMind.GeoIP2 -Version 2.4.0 for 2.4.0.)

Herewith attached error screen short

**Comment by Ethirajparthasarathi** [comment]
hi Gregory,

i am already try this but not install.[Install-Package MaxMind.GeoIP2 -Pre for
the beta or Install-Package MaxMind.GeoIP2 -Version 2.4.0 for 2.4.0.]

Regards
Ethiraj Parthasarathi

**Comment by oschwald** [comment]
From your screenshots, it appears you are trying to install the MaxMind.GeoIP2 package into the GeoIP2 solution rather than the solution from your project. I suggest asking for help on StackOverflow as this is a general dependency management question and not specific to this library.
