### ISSUE TITLE
How to consume geoip .net api or webservice from C# 2.0 based app

### ISSUE THREAD

**Issue by Software2Life** [maxmind/GeoIP2-dotnet#69]
Hi Team,

We have bought licence of maxmind to use geoip to get location details of user registering on our website.
As part of integration with maxmind geoip's .net api with our .net based client, we understand we have to use these 2 nuget packages, which can be added to app done in .net framework 4.5, but in our case we have to consume geoip from webservice done in .net 2.0 and we can't migrate it to higher version, at least not soon. 
Nugets:
https://www.nuget.org/packages/MaxMind.GeoIP2/
https://www.nuget.org/packages/MaxMind.Db/

Hence please let us know how can we consume maxmind geoip api in .net 2.0 app, either using any older version of your nuget packages or any direct webservice urls for instance of maxmind(also any documentation location for same for C# client).

If issue is not right place for such queries/concerns, then please move it to right place and please give us your inputs/solutions for issues we are facing. Thanks.

**Comment by oschwald** [comment]
This API requires .NET 4.5. No versions of this support .NET 2.0. You could try our deprecated [GeoIP Legacy API](https://github.com/maxmind/geoip-api-csharp2).

Greg
MaxMind

**Comment by Software2Life** [comment]
Thanks for information, with your input; we have taken decision to upgrade to 4.5 then, as not left with any current versions which supports 2.0.
