### ISSUE TITLE
Cache the database

### ISSUE THREAD

**Issue by petekcchen** [maxmind/GeoIP2-dotnet#71]
Hi,

Is there any suggested practice to cache the database (the one I'm using is GeoIP2-Country.mmdb)?

What I would like to do is, when my web applications launch, I cache the database so that for every coming requests, I can look up the cache directly instead of instantiate DatabaseReader every time. And if there's updated database, I can overwrite the old one while my applications are still running.

Would that be possible? Thanks.

**Comment by oschwald** [comment]
Yes. The `DatabaseReader` is [thread-safe](https://github.com/maxmind/GeoIP2-dotnet#multi-threaded-use). You can share it across threads without issue and replace it with a new one when you updated the database.

**Comment by t-nakajimaa** [comment]
If I use maxmind/geoipupdate to automatically update the DB, will DatabaseReader detect the change and reload the DB files? Or do I need to restart the app after updating?

**Comment by oschwald** [comment]
You will need to reopen the reader.
