### ISSUE TITLE
Code not reflecting on NuGet

### ISSUE THREAD

**Issue by Mackanga** [maxmind/GeoIP2-dotnet#79]
Hello, not too sure if its just me but i downloaded the NuGet package, just as the readme said in this file "install-package MaxMind.GeoIP2" upon trying to use the ASN database it does not exist, yet in this project it says it does. Is there anything missing? As i needed to use the ASN database for a project of mine but isnt coming up in my NuGet package. Would it be updated soon or how else can i install?
Thanks in advance.

**Comment by oschwald** [comment]
We have not done a release with ASN support yet. We expect to release this in the next few weeks.

**Comment by oschwald** [comment]
Closing as we did a release with ASN several weeks ago.
