### ISSUE TITLE
Why is sending user id and license key through constructor?

### ISSUE THREAD

**Issue by nukec** [maxmind/GeoIP2-dotnet#88]
Why do we have to create concrete instance `var client = new WebServiceClient(uid, licenseKey);` to get response back? This is antipattern

**Comment by oschwald** [comment]
The account ID and license key are necessary for use of any of the methods. Further, the classes are intentionally immutable, which make using in a multithreaded environment safer and their behavior easier to understand. I am not sure I follow how this prevents unit testing. You may substitute our the class with a mock.
