### ISSUE TITLE
DatabaseReader is IDisposable for no reason

### ISSUE THREAD

**Issue by mabead** [maxmind/GeoIP2-dotnet#94]
When I look at the code, I see that the `DatabaseReader` is `IDisposable`. The implementation of `Dispose` simply disposes the sub reader here https://github.com/maxmind/GeoIP2-dotnet/blob/346c8a83a009cb9aa729c85210597df0511e6c32/MaxMind.GeoIP2/DatabaseReader.cs#L95

Then, the `Reader` calls the Dispose of the buffer https://github.com/maxmind/MaxMind-DB-Reader-dotnet/blob/e229436fb61a15a545ecaae400060e9af2dbd54d/MaxMind.Db/Reader.cs#L225.

The `Buffer` is an `ArrayBuffer` that is also `IDisposable` but the implementation of `Dispose` has nothing to do since it only keeps data in memory: https://github.com/maxmind/MaxMind-DB-Reader-dotnet/blob/e229436fb61a15a545ecaae400060e9af2dbd54d/MaxMind.Db/ArrayBuffer.cs#L113 

So, if my understanding is right, all this chain of `IDisposable` does nothing in the end and complexifies all the consumers that must properly Dispose the DatabaseReader. If possible, please consider removing `IDisposable` from `DatabaseReader`.

**Comment by oschwald** [comment]
The `Buffer` is not necessarily an `ArrayBuffer`. If you open the database from a file, the default behavior will be to use a `MemoryMapBuffer`. The `MemoryMappedFile` [needs to be disposed](https://github.com/maxmind/MaxMind-DB-Reader-dotnet/blob/master/MaxMind.Db/MemoryMapBuffer.cs#L125-L126).

**Comment by mabead** [comment]
Ok, I guess I didn't understand the code correctly. Thanks for letting me know.
